export const CONFIG = {
  NITRADO_TOKEN: process.env.NITRADO_TOKEN!,
  DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN!,
  DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID!,
  DISCORD_FORUM_CHANNEL_ID: process.env.DISCORD_FORUM_CHANNEL_ID!,
  PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID!,
  PAYPAL_CLIENT_SECRET: process.env.PAYPAL_CLIENT_SECRET!,
  PAYPAL_PLAN_MONTHLY: process.env.PAYPAL_PLAN_MONTHLY!,
  PAYPAL_PLAN_QUARTERLY: process.env.PAYPAL_PLAN_QUARTERLY!,
  PAYPAL_WEBHOOK_ID: process.env.PAYPAL_WEBHOOK_ID!,
  PAYPAL_API_BASE: process.env.PAYPAL_API_BASE || 'https://api-m.sandbox.paypal.com',
};
